In [1]:
pip install seaborn

DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/volatility3-2.7.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in /Users/emrecanerol/Library/Python/3.11/lib/python/site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from seaborn) (3.8.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.49.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/emrecanerol/Library/Python/3.11/lib/python/site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/emrecanerol/Library/Python/3.11/lib/python/site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
player_data = pd.read_csv('./variables.csv')

In [4]:
player_data.describe

<bound method NDFrame.describe of       Unnamed: 0              Name  Apps    Mins    Mins/Gm  Height  Weight  \
0              0   Josip Mijatović  12.0   809.0  67.416667   173.0    68.0
1              1     Duje Ninčević  15.0  1161.0  77.400000   172.0    69.0
2              2   Marin Karabatić  15.0  1350.0  90.000000   170.0    62.0
3              3      Vicko Ševelj  20.0  1738.0  86.900000   192.0    86.0
4              4     Fran Vujnović  15.0  1384.0  92.266667   190.0    77.0
...          ...               ...   ...     ...        ...     ...     ...
1117        1117      Sergio Ramos  11.0   924.0  84.000000   184.0    82.0
1118        1118        Marquinhos  13.0  1129.0  86.846154   183.0    75.0
1119        1119  Thibaut Courtois  19.0  1710.0  90.000000   199.0    96.0
1120        1120    Raphaël Varane  17.0  1463.0  86.058824   191.0    81.0
1121        1121         Jan Oblak  19.0  1687.0  88.789474   189.0    84.0

      Age  Av Rat  Gls  ...  Off                           Based  Tck R   CA  \
0      20    7.14  1.0  ...  0.0          Croatia (3. HNL Zapad)   0.88   84
1      25    6.84  0.0  ...  0.0            Croatia (3. HNL Jug)   0.76   79
2      22    6.90  0.0  ...  0.0            Croatia (3. HNL Jug)   0.77   87
3      22    7.15  1.0  ...  1.0  Bosnia & Herzegovina (Liga 12)   0.88   95
4      19    7.23  4.0  ...  0.0          Croatia (3. HNL Istok)   0.93   83
...   ...     ...  ...  ...  ...                             ...    ...  ...
1117   36    7.15  0.0  ...  0.0                France (Ligue 1)   0.74  156
1118   28    7.33  1.0  ...  1.0                France (Ligue 1)   1.00  163
1119   30    7.42  0.0  ...  0.0                  Spain (LaLiga)   0.33  180
1120   29    7.36  0.0  ...  2.0        England (Premier League)   0.81  164
1121   29    7.01  0.0  ...  0.0                  Spain (LaLiga)   0.00  178

      Saves  Saves/xSv%    Gls/xG  Dist/Mins  Transfer Value        Value
0       0.0    0.000000  5.555556   0.126823       €3K - €9K       6000.0
1       0.0    0.000000  0.000000   0.129457      €0 - €2.5K       1250.0
2       0.0    0.000000  0.000000   0.128000       €0 - €12K       6000.0
3       0.0    0.000000  2.380952   0.058631     €100K - €1M     550000.0
4       0.0    0.000000  0.000000   0.016040    €14K - €150K      82000.0
...     ...         ...       ...        ...             ...          ...
1117    0.0    0.000000  0.000000   0.123268     €12M - €18M   15000000.0
1118    0.0    0.000000  3.448276   0.126749    €99M - €128M  113500000.0
1119   48.0   -0.848956  0.000000   0.072982   €172M - €225M  198500000.0
1120    0.0    0.000000  0.000000   0.107792   €101M - €127M  114000000.0
1121   45.0   -3.118503  0.000000   0.067635   €112M - €178M  145000000.0

[1122 rows x 45 columns]>

In [5]:
player_data.head()

,Unnamed: 0,Name,Apps,Mins,Mins/Gm,Height,Weight,Age,Av Rat,Gls,...,Off,Based,Tck R,CA,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Transfer Value,Value
0,0,Josip Mijatović,12.0,809.0,67.416667,173.0,68.0,20,7.14,1.0,...,0.0,Croatia (3. HNL Zapad),0.88,84,0.0,0.0,5.555556,0.126823,€3K - €9K,6000.0
1,1,Duje Ninčević,15.0,1161.0,77.400000,172.0,69.0,25,6.84,0.0,...,0.0,Croatia (3. HNL Jug),0.76,79,0.0,0.0,0.000000,0.129457,€0 - €2.5K,1250.0
2,2,Marin Karabatić,15.0,1350.0,90.000000,170.0,62.0,22,6.90,0.0,...,0.0,Croatia (3. HNL Jug),0.77,87,0.0,0.0,0.000000,0.128000,€0 - €12K,6000.0
3,3,Vicko Ševelj,20.0,1738.0,86.900000,192.0,86.0,22,7.15,1.0,...,1.0,Bosnia & Herzegovina (Liga 12),0.88,95,0.0,0.0,2.380952,0.058631,€100K - €1M,550000.0
4,4,Fran Vujnović,15.0,1384.0,92.266667,190.0,77.0,19,7.23,4.0,...,0.0,Croatia (3. HNL Istok),0.93,83,0.0,0.0,0.000000,0.016040,€14K - €150K,82000.0

In [6]:
player_data.tail()

,Unnamed: 0,Name,Apps,Mins,Mins/Gm,Height,Weight,Age,Av Rat,Gls,...,Off,Based,Tck R,CA,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Transfer Value,Value
1117,1117,Sergio Ramos,11.0,924.0,84.000000,184.0,82.0,36,7.15,0.0,...,0.0,France (Ligue 1),0.74,156,0.0,0.000000,0.000000,0.123268,€12M - €18M,15000000.0
1118,1118,Marquinhos,13.0,1129.0,86.846154,183.0,75.0,28,7.33,1.0,...,1.0,France (Ligue 1),1.00,163,0.0,0.000000,3.448276,0.126749,€99M - €128M,113500000.0
1119,1119,Thibaut Courtois,19.0,1710.0,90.000000,199.0,96.0,30,7.42,0.0,...,0.0,Spain (LaLiga),0.33,180,48.0,-0.848956,0.000000,0.072982,€172M - €225M,198500000.0
1120,1120,Raphaël Varane,17.0,1463.0,86.058824,191.0,81.0,29,7.36,0.0,...,2.0,England (Premier League),0.81,164,0.0,0.000000,0.000000,0.107792,€101M - €127M,114000000.0
1121,1121,Jan Oblak,19.0,1687.0,88.789474,189.0,84.0,29,7.01,0.0,...,0.0,Spain (LaLiga),0.00,178,45.0,-3.118503,0.000000,0.067635,€112M - €178M,145000000.0

In [7]:
player_data.shape

(1122, 45)

In [8]:
player_data.size

50490

In [9]:
player_data.info

<bound method DataFrame.info of       Unnamed: 0              Name  Apps    Mins    Mins/Gm  Height  Weight  \
0              0   Josip Mijatović  12.0   809.0  67.416667   173.0    68.0
1              1     Duje Ninčević  15.0  1161.0  77.400000   172.0    69.0
2              2   Marin Karabatić  15.0  1350.0  90.000000   170.0    62.0
3              3      Vicko Ševelj  20.0  1738.0  86.900000   192.0    86.0
4              4     Fran Vujnović  15.0  1384.0  92.266667   190.0    77.0
...          ...               ...   ...     ...        ...     ...     ...
1117        1117      Sergio Ramos  11.0   924.0  84.000000   184.0    82.0
1118        1118        Marquinhos  13.0  1129.0  86.846154   183.0    75.0
1119        1119  Thibaut Courtois  19.0  1710.0  90.000000   199.0    96.0
1120        1120    Raphaël Varane  17.0  1463.0  86.058824   191.0    81.0
1121        1121         Jan Oblak  19.0  1687.0  88.789474   189.0    84.0

      Age  Av Rat  Gls  ...  Off                           Based  Tck R   CA  \
0      20    7.14  1.0  ...  0.0          Croatia (3. HNL Zapad)   0.88   84
1      25    6.84  0.0  ...  0.0            Croatia (3. HNL Jug)   0.76   79
2      22    6.90  0.0  ...  0.0            Croatia (3. HNL Jug)   0.77   87
3      22    7.15  1.0  ...  1.0  Bosnia & Herzegovina (Liga 12)   0.88   95
4      19    7.23  4.0  ...  0.0          Croatia (3. HNL Istok)   0.93   83
...   ...     ...  ...  ...  ...                             ...    ...  ...
1117   36    7.15  0.0  ...  0.0                France (Ligue 1)   0.74  156
1118   28    7.33  1.0  ...  1.0                France (Ligue 1)   1.00  163
1119   30    7.42  0.0  ...  0.0                  Spain (LaLiga)   0.33  180
1120   29    7.36  0.0  ...  2.0        England (Premier League)   0.81  164
1121   29    7.01  0.0  ...  0.0                  Spain (LaLiga)   0.00  178

      Saves  Saves/xSv%    Gls/xG  Dist/Mins  Transfer Value        Value
0       0.0    0.000000  5.555556   0.126823       €3K - €9K       6000.0
1       0.0    0.000000  0.000000   0.129457      €0 - €2.5K       1250.0
2       0.0    0.000000  0.000000   0.128000       €0 - €12K       6000.0
3       0.0    0.000000  2.380952   0.058631     €100K - €1M     550000.0
4       0.0    0.000000  0.000000   0.016040    €14K - €150K      82000.0
...     ...         ...       ...        ...             ...          ...
1117    0.0    0.000000  0.000000   0.123268     €12M - €18M   15000000.0
1118    0.0    0.000000  3.448276   0.126749    €99M - €128M  113500000.0
1119   48.0   -0.848956  0.000000   0.072982   €172M - €225M  198500000.0
1120    0.0    0.000000  0.000000   0.107792   €101M - €127M  114000000.0
1121   45.0   -3.118503  0.000000   0.067635   €112M - €178M  145000000.0

[1122 rows x 45 columns]>

In [10]:
player_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,1122.0,5.605000e+02,3.240378e+02,0.000000,280.250000,5.605000e+02,8.407500e+02,1.121000e+03
Apps,1122.0,1.514171e+01,5.617806e+00,11.000000,12.000000,1.400000e+01,1.600000e+01,5.000000e+01
Mins,1122.0,1.316807e+03,5.038894e+02,756.000000,1012.500000,1.170000e+03,1.412250e+03,4.514000e+03
Mins/Gm,1122.0,8.680776e+01,5.570130e+00,63.000000,84.165385,8.852273e+01,9.000000e+01,1.153636e+02
Height,1122.0,1.844626e+02,6.632774e+00,161.000000,180.000000,1.850000e+02,1.890000e+02,2.040000e+02
Weight,1122.0,7.781907e+01,7.308194e+00,56.000000,73.000000,7.800000e+01,8.200000e+01,1.060000e+02
Age,1122.0,2.628520e+01,3.350308e+00,18.000000,24.000000,2.600000e+01,2.900000e+01,3.900000e+01
Av Rat,1122.0,7.008619e+00,2.191846e-01,6.360000,6.860000,7.000000e+00,7.150000e+00,8.170000e+00
Gls,1122.0,7.352941e-01,1.143723e+00,0.000000,0.000000,0.000000e+00,1.000000e+00,9.000000e+00
Gls/90,1122.0,5.074866e-02,7.847891e-02,0.000000,0.000000,0.000000e+00,8.000000e-02,5.700000e-01
Shot %,1122.0,2.185651e-01,1.942060e-01,0.000000,0.000000,2.100000e-01,3.300000e-01,1.000000e+00
Pen/R,1122.0,2.529412e-02,1.558698e-01,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000e+00
xG,1122.0,8.053654e-01,8.162525e-01,0.000000,0.160000,6.100000e-01,1.220000e+00,7.450000e+00
Ch C/90,1122.0,2.467380e-01,4.095578e-01,0.000000,0.000000,1.000000e-01,3.000000e-01,3.840000e+00
Asts/90,1122.0,7.735294e-02,1.038975e-01,0.000000,0.000000,6.000000e-02,1.100000e-01,6.500000e-01
K Ps/90,1122.0,5.630125e-01,5.435204e-01,0.000000,0.130000,3.200000e-01,9.600000e-01,3.450000e+00
Pas %,1122.0,8.449465e-01,1.494690e-01,0.240000,0.852500,9.000000e-01,9.300000e-01,9.900000e-01
Cr C/A,1122.0,1.787166e-01,2.361574e-01,0.000000,0.000000,1.000000e-01,2.800000e-01,1.000000e+00
Drb/90,1122.0,2.557398e-01,4.732359e-01,0.000000,0.000000,9.000000e-02,2.800000e-01,3.250000e+00
Distance,1122.0,1.336912e+02,5.542615e+01,1.600000,107.800000,1.334500e+02,1.605250e+02,4.816000e+02
Hdr %,1122.0,6.260428e-01,2.924888e-01,0.000000,0.600000,7.400000e-01,8.100000e-01,1.000000e+00
K Tck,1122.0,1.154189e+00,1.494661e+00,0.000000,0.000000,1.000000e+00,2.000000e+00,8.000000e+00
Fls,1122.0,1.434848e+01,1.087914e+01,0.000000,8.000000,1.400000e+01,1.900000e+01,8.400000e+01
Int/90,1122.0,1.586524e+00,1.094684e+00,0.000000,0.702500,1.545000e+00,2.550000e+00,4.420000e+00
Clear,1122.0,5.891622e+01,5.323995e+01,0.000000,15.000000,3.950000e+01,1.040000e+02,3.160000e+02
Con/90,1122.0,1.931729e-01,4.631430e-01,0.000000,0.000000,0.000000e+00,0.000000e+00,2.630000e+00
xSv %,1122.0,-1.070490e+00,1.413747e+01,-221.580000,0.000000,0.000000e+00,0.000000e+00,2.290900e+02
Sv %,1122.0,-7.745098e-03,3.791623e-02,-0.660000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
Svh,1122.0,1.850267e+00,5.214818e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,5.400000e+01
Svt,1122.0,1.199643e+00,3.224748e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,2.800000e+01
Svp,1122.0,3.594474e+00,9.179666e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,8.300000e+01
Pens Saved Ratio,1122.0,2.464349e-02,1.407065e-01,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000e+00
PoM,1122.0,6.996435e-01,9.704739e-01,0.000000,0.000000,0.000000e+00,1.000000e+00,8.000000e+00
Aer A/90,1122.0,7.211863e+00,5.339191e+00,0.000000,3.062500,6.270000e+00,1.266250e+01,1.978000e+01
Off,1122.0,1.004456e+00,1.607570e+00,0.000000,0.000000,0.000000e+00,1.000000e+00,1.300000e+01
Tck R,1122.0,7.080481e-01,2.965379e-01,0.000000,0.670000,8.100000e-01,8.975000e-01,1.000000e+00
CA,1122.0,1.181310e+02,2.018301e+01,70.000000,103.000000,1.170000e+02,1.300000e+02,1.800000e+02
Saves,1122.0,6.644385e+00,1.696702e+01,0.000000,0.000000,0.000000e+00,0.000000e+00,1.440000e+02
Saves/xSv%,1122.0,-1.265223e-01,9.534647e-01,-14.689266,0.000000,0.000000e+00,0.000000e+00,4.694109e-01
Gls/xG,1122.0,1.285594e+00,5.297611e+00,0.000000,0.000000,0.000000e+00,1.282051e+00,1.000000e+02
Dist/Mins,1122.0,1.059838e-01,3.551151e-02,0.000930,0.075932,1.160712e-01,1.340177e-01,1.604096e-01
Value,1122.0,1.154190e+07,3.039308e+07,750.000000,165000.000000,1.265000e+06,6.537500e+06,3.045000e+08

In [11]:
player_data.columns

Index(['Unnamed: 0', 'Name', 'Apps', 'Mins', 'Mins/Gm', 'Height', 'Weight',
       'Age', 'Av Rat', 'Gls', 'Gls/90', 'Shot %', 'Pen/R', 'xG', 'Ch C/90',
       'Asts/90', 'K Ps/90', 'Pas %', 'Cr C/A', 'Drb/90', 'Distance', 'Hdr %',
       'K Tck', 'Fls', 'Int/90', 'Clear', 'Con/90', 'xSv %', 'Sv %', 'Svh',
       'Svt', 'Svp', 'Pens Saved Ratio', 'PoM', 'Aer A/90', 'Off', 'Based',
       'Tck R', 'CA', 'Saves', 'Saves/xSv%', 'Gls/xG', 'Dist/Mins',
       'Transfer Value', 'Value'],
      dtype='object')

In [12]:
player_data.isnull()

,Unnamed: 0,Name,Apps,Mins,Mins/Gm,Height,Weight,Age,Av Rat,Gls,...,Off,Based,Tck R,CA,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Transfer Value,Value
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1118,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1119,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1120,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1121,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
player_data.isnull().values.any()

False

In [14]:
player_data.isnull().sum()

Unnamed: 0          0
Name                0
Apps                0
Mins                0
Mins/Gm             0
Height              0
Weight              0
Age                 0
Av Rat              0
Gls                 0
Gls/90              0
Shot %              0
Pen/R               0
xG                  0
Ch C/90             0
Asts/90             0
K Ps/90             0
Pas %               0
Cr C/A              0
Drb/90              0
Distance            0
Hdr %               0
K Tck               0
Fls                 0
Int/90              0
Clear               0
Con/90              0
xSv %               0
Sv %                0
Svh                 0
Svt                 0
Svp                 0
Pens Saved Ratio    0
PoM                 0
Aer A/90            0
Off                 0
Based               0
Tck R               0
CA                  0
Saves               0
Saves/xSv%          0
Gls/xG              0
Dist/Mins           0
Transfer Value      0
Value               0
dtype: int64

In [17]:
for col in player_data.columns:
    X = player_data.drop(columns=[col]).values
    y = player_data[col].values

In [18]:
data_indexes= np.arange(len(X))
np.random.shuffle(data_indexes)

In [19]:
k_value = 10
fold_size = len(X) // k_value

In [20]:
for i in range(k_value):
    test_data = data_indexes[i*fold_size: (i+1) * fold_size]
    train_data = np.concatenate([data_indexes[:i * fold_size],
                                 data_indexes[(i+1) * fold_size: ]])
    
    X_train, X_test = X[train_data], X[test_data]
    y_train, y_test = y[train_data], y[test_data]