In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
player_data = pd.read_csv('./variables.csv')
player_data.describe

<bound method NDFrame.describe of       Unnamed: 0              Name  Apps    Mins    Mins/Gm  Height  Weight  \
0              0   Josip Mijatović  12.0   809.0  67.416667   173.0    68.0
1              1     Duje Ninčević  15.0  1161.0  77.400000   172.0    69.0
2              2   Marin Karabatić  15.0  1350.0  90.000000   170.0    62.0
3              3      Vicko Ševelj  20.0  1738.0  86.900000   192.0    86.0
4              4     Fran Vujnović  15.0  1384.0  92.266667   190.0    77.0
...          ...               ...   ...     ...        ...     ...     ...
1117        1117      Sergio Ramos  11.0   924.0  84.000000   184.0    82.0
1118        1118        Marquinhos  13.0  1129.0  86.846154   183.0    75.0
1119        1119  Thibaut Courtois  19.0  1710.0  90.000000   199.0    96.0
1120        1120    Raphaël Varane  17.0  1463.0  86.058824   191.0    81.0
1121        1121         Jan Oblak  19.0  1687.0  88.789474   189.0    84.0

      Age  Av Rat  Gls  ...  Off                           Based  Tck R   CA  \
0      20    7.14  1.0  ...  0.0          Croatia (3. HNL Zapad)   0.88   84
1      25    6.84  0.0  ...  0.0            Croatia (3. HNL Jug)   0.76   79
2      22    6.90  0.0  ...  0.0            Croatia (3. HNL Jug)   0.77   87
3      22    7.15  1.0  ...  1.0  Bosnia & Herzegovina (Liga 12)   0.88   95
4      19    7.23  4.0  ...  0.0          Croatia (3. HNL Istok)   0.93   83
...   ...     ...  ...  ...  ...                             ...    ...  ...
1117   36    7.15  0.0  ...  0.0                France (Ligue 1)   0.74  156
1118   28    7.33  1.0  ...  1.0                France (Ligue 1)   1.00  163
1119   30    7.42  0.0  ...  0.0                  Spain (LaLiga)   0.33  180
1120   29    7.36  0.0  ...  2.0        England (Premier League)   0.81  164
1121   29    7.01  0.0  ...  0.0                  Spain (LaLiga)   0.00  178

      Saves  Saves/xSv%    Gls/xG  Dist/Mins  Transfer Value        Value
0       0.0    0.000000  5.555556   0.126823       €3K - €9K       6000.0
1       0.0    0.000000  0.000000   0.129457      €0 - €2.5K       1250.0
2       0.0    0.000000  0.000000   0.128000       €0 - €12K       6000.0
3       0.0    0.000000  2.380952   0.058631     €100K - €1M     550000.0
4       0.0    0.000000  0.000000   0.016040    €14K - €150K      82000.0
...     ...         ...       ...        ...             ...          ...
1117    0.0    0.000000  0.000000   0.123268     €12M - €18M   15000000.0
1118    0.0    0.000000  3.448276   0.126749    €99M - €128M  113500000.0
1119   48.0   -0.848956  0.000000   0.072982   €172M - €225M  198500000.0
1120    0.0    0.000000  0.000000   0.107792   €101M - €127M  114000000.0
1121   45.0   -3.118503  0.000000   0.067635   €112M - €178M  145000000.0

[1122 rows x 45 columns]>

In [53]:
player_data.head()

,Unnamed: 0,Name,Apps,Mins,Mins/Gm,Height,Weight,Age,Av Rat,Gls,...,Off,Based,Tck R,CA,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Transfer Value,Value
0,0,Josip Mijatović,12.0,809.0,67.416667,173.0,68.0,20,7.14,1.0,...,0.0,Croatia (3. HNL Zapad),0.88,84,0.0,0.0,5.555556,0.126823,€3K - €9K,6000.0
1,1,Duje Ninčević,15.0,1161.0,77.400000,172.0,69.0,25,6.84,0.0,...,0.0,Croatia (3. HNL Jug),0.76,79,0.0,0.0,0.000000,0.129457,€0 - €2.5K,1250.0
2,2,Marin Karabatić,15.0,1350.0,90.000000,170.0,62.0,22,6.90,0.0,...,0.0,Croatia (3. HNL Jug),0.77,87,0.0,0.0,0.000000,0.128000,€0 - €12K,6000.0
3,3,Vicko Ševelj,20.0,1738.0,86.900000,192.0,86.0,22,7.15,1.0,...,1.0,Bosnia & Herzegovina (Liga 12),0.88,95,0.0,0.0,2.380952,0.058631,€100K - €1M,550000.0
4,4,Fran Vujnović,15.0,1384.0,92.266667,190.0,77.0,19,7.23,4.0,...,0.0,Croatia (3. HNL Istok),0.93,83,0.0,0.0,0.000000,0.016040,€14K - €150K,82000.0

In [54]:
# Oyuncunun tahmini bonservis değer aralığını, minimum ve maximum olarak iki farklı sütuna ayırarak minimum bonservis bedeli, maksimum bonservis bedeli şeklinde ayırıyoruz

# Splitting the "Transfer value" column into two separate columns
player_data[['Min Transfer Value', 'Max Transfer Value']] = player_data['Transfer Value'].str.split('-', expand=True)

def convert_to_numeric(value):
    if value is not None:
        value = value.strip()  # Remove leading and trailing whitespaces
        if value.endswith('K'):
            return float(value.replace('€', '').replace('K', '')) * 1000
        elif value.endswith('M'):
            return float(value.replace('€', '').replace('M', '')) * 1000000
        else:
            return float(value.replace('€', ''))
    else:
        return None  # Return None for missing values

# Applying the conversion function to the columns
player_data['Min Transfer Value'] = player_data['Min Transfer Value'].apply(convert_to_numeric)
player_data['Max Transfer Value'] = player_data['Max Transfer Value'].apply(convert_to_numeric)

# Displaying the DataFrame
player_data.drop(columns=['Transfer Value'],inplace=True)

In [55]:
player_data

,Unnamed: 0,Name,Apps,Mins,Mins/Gm,Height,Weight,Age,Av Rat,Gls,...,Based,Tck R,CA,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Value,Min Transfer Value,Max Transfer Value
0,0,Josip Mijatović,12.0,809.0,67.416667,173.0,68.0,20,7.14,1.0,...,Croatia (3. HNL Zapad),0.88,84,0.0,0.000000,5.555556,0.126823,6000.0,3000.0,9000.0
1,1,Duje Ninčević,15.0,1161.0,77.400000,172.0,69.0,25,6.84,0.0,...,Croatia (3. HNL Jug),0.76,79,0.0,0.000000,0.000000,0.129457,1250.0,0.0,2500.0
2,2,Marin Karabatić,15.0,1350.0,90.000000,170.0,62.0,22,6.90,0.0,...,Croatia (3. HNL Jug),0.77,87,0.0,0.000000,0.000000,0.128000,6000.0,0.0,12000.0
3,3,Vicko Ševelj,20.0,1738.0,86.900000,192.0,86.0,22,7.15,1.0,...,Bosnia & Herzegovina (Liga 12),0.88,95,0.0,0.000000,2.380952,0.058631,550000.0,100000.0,1000000.0
4,4,Fran Vujnović,15.0,1384.0,92.266667,190.0,77.0,19,7.23,4.0,...,Croatia (3. HNL Istok),0.93,83,0.0,0.000000,0.000000,0.016040,82000.0,14000.0,150000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,1117,Sergio Ramos,11.0,924.0,84.000000,184.0,82.0,36,7.15,0.0,...,France (Ligue 1),0.74,156,0.0,0.000000,0.000000,0.123268,15000000.0,12000000.0,18000000.0
1118,1118,Marquinhos,13.0,1129.0,86.846154,183.0,75.0,28,7.33,1.0,...,France (Ligue 1),1.00,163,0.0,0.000000,3.448276,0.126749,113500000.0,99000000.0,128000000.0
1119,1119,Thibaut Courtois,19.0,1710.0,90.000000,199.0,96.0,30,7.42,0.0,...,Spain (LaLiga),0.33,180,48.0,-0.848956,0.000000,0.072982,198500000.0,172000000.0,225000000.0
1120,1120,Raphaël Varane,17.0,1463.0,86.058824,191.0,81.0,29,7.36,0.0,...,England (Premier League),0.81,164,0.0,0.000000,0.000000,0.107792,114000000.0,101000000.0,127000000.0
1121,1121,Jan Oblak,19.0,1687.0,88.789474,189.0,84.0,29,7.01,0.0,...,Spain (LaLiga),0.00,178,45.0,-3.118503,0.000000,0.067635,145000000.0,112000000.0,178000000.0

In [56]:
from sklearn.preprocessing import LabelEncoder

# Assuming df is your DataFrame and 'column_name' is the name of the column containing strings
column_name = 'Based'

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit LabelEncoder to the unique values in the column and transform the column
encoded_column = label_encoder.fit_transform(player_data[column_name])

# Print the mapping of original strings to encoded numbers
print("Mapping of original strings to encoded numbers:")
for label, string in enumerate(label_encoder.classes_):
    print(f"{string}: {label}")

# Replace the original column with the encoded column
player_data[column_name + '_encoded'] = encoded_column
player_data.drop(columns='Based', inplace=True)

Mapping of original strings to encoded numbers:
Argentina (Liga Profesional): 0
Austria (ADMIRAL 2. Liga): 1
Austria (Admiral Bundesliga): 2
Belgium (1B Pro League): 3
Belgium (Eerste nationale): 4
Belgium (Pro League): 5
Bosnia & Herzegovina (Liga 12): 6
Brazil (Brasileiro Série A): 7
Brazil (Campeonato Brasileiro Série B): 8
Chile (Primera División): 9
China (CFA Super League): 10
Colombia (Categoría Primera A): 11
Croatia (3. HNL Istok): 12
Croatia (3. HNL Jug): 13
Croatia (3. HNL Zapad): 14
Croatia (Druga HNL): 15
Croatia (Prva HNL): 16
Croatia (Regionalne Lige - Sibenik): 17
Cyprus (A' Katigorías): 18
DR Congo (Vodacom Ligue 1): 19
Denmark (Superliga): 20
Ecuador (Serie A): 21
England (EFL Championship): 22
England (EFL League One): 23
England (Premier League): 24
France (Ligue 1): 25
France (Ligue 2): 26
France (National 2 Groupe A): 27
France (National 2 Groupe B): 28
France (National 2 Groupe C): 29
France (National 2 Groupe D): 30
France (National 3 Auvergne-Rhône-Alpes): 31
France (National 3 Hauts-de-France): 32
France (National 3 Méditerranée-Corse): 33
France (National 3 Nouvelle-Aquitaine): 34
France (National 3 Pays de la Loire): 35
France (National 3 Île-de-France): 36
Germany (2. Bundesliga): 37
Germany (Bundesliga): 38
Holland (Eerste Divisie): 39
Holland (Eredivisie): 40
Hungary (OTP Bank Liga): 41
Israel (Ligat Ha'Al): 42
Italy (Lega Nazionale Dilettanti A): 43
Italy (Lega Nazionale Dilettanti C): 44
Italy (Lega Nazionale Dilettanti D): 45
Italy (Lega Nazionale Dilettanti E): 46
Italy (Lega Nazionale Dilettanti F): 47
Italy (Lega Nazionale Dilettanti H): 48
Italy (Serie A): 49
Italy (Serie B): 50
Italy (Serie C/A): 51
Italy (Serie C/B): 52
Mexico (Liga BBVA MX): 53
Moldova (Divizia Naţională): 54
Norway (Eliteserien): 55
Paraguay (Primera División): 56
Poland (Ekstraklasa): 57
Portugal (Campeonato D`Elite Série 2 Porto): 58
Portugal (Campeonato Safina - Aveiro): 59
Portugal (Campeonato dos Açores - Ponta Delgada): 60
Portugal (FPF Liga 3): 61
Portugal (Liga 3 Norte): 62
Portugal (Liga 3 Sul): 63
Portugal (Liga Portugal 2): 64
Portugal (Primeira Divisão - Castelo Branco): 65
Portugal (Primeira Liga): 66
Portugal (Pro-Nacional - Braga): 67
Romania (Liga I): 68
Russia (Premier Liga): 69
Serbia (Super liga): 70
Slovenia (1. SNL): 71
Slovenia (2. SNL): 72
Spain (LaLiga 2): 73
Spain (LaLiga): 74
Sweden (Allsvenskan): 75
Switzerland (Challenge League): 76
Switzerland (Super League): 77
Turkey (Süper Lig): 78
U.S.A. (MLS): 79
Ukraine (Favbet Liha): 80
Uruguay (Campeonato Uruguayo): 81

In [57]:
player_data

,Unnamed: 0,Name,Apps,Mins,Mins/Gm,Height,Weight,Age,Av Rat,Gls,...,Tck R,CA,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Value,Min Transfer Value,Max Transfer Value,Based_encoded
0,0,Josip Mijatović,12.0,809.0,67.416667,173.0,68.0,20,7.14,1.0,...,0.88,84,0.0,0.000000,5.555556,0.126823,6000.0,3000.0,9000.0,14
1,1,Duje Ninčević,15.0,1161.0,77.400000,172.0,69.0,25,6.84,0.0,...,0.76,79,0.0,0.000000,0.000000,0.129457,1250.0,0.0,2500.0,13
2,2,Marin Karabatić,15.0,1350.0,90.000000,170.0,62.0,22,6.90,0.0,...,0.77,87,0.0,0.000000,0.000000,0.128000,6000.0,0.0,12000.0,13
3,3,Vicko Ševelj,20.0,1738.0,86.900000,192.0,86.0,22,7.15,1.0,...,0.88,95,0.0,0.000000,2.380952,0.058631,550000.0,100000.0,1000000.0,6
4,4,Fran Vujnović,15.0,1384.0,92.266667,190.0,77.0,19,7.23,4.0,...,0.93,83,0.0,0.000000,0.000000,0.016040,82000.0,14000.0,150000.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,1117,Sergio Ramos,11.0,924.0,84.000000,184.0,82.0,36,7.15,0.0,...,0.74,156,0.0,0.000000,0.000000,0.123268,15000000.0,12000000.0,18000000.0,25
1118,1118,Marquinhos,13.0,1129.0,86.846154,183.0,75.0,28,7.33,1.0,...,1.00,163,0.0,0.000000,3.448276,0.126749,113500000.0,99000000.0,128000000.0,25
1119,1119,Thibaut Courtois,19.0,1710.0,90.000000,199.0,96.0,30,7.42,0.0,...,0.33,180,48.0,-0.848956,0.000000,0.072982,198500000.0,172000000.0,225000000.0,74
1120,1120,Raphaël Varane,17.0,1463.0,86.058824,191.0,81.0,29,7.36,0.0,...,0.81,164,0.0,0.000000,0.000000,0.107792,114000000.0,101000000.0,127000000.0,24
1121,1121,Jan Oblak,19.0,1687.0,88.789474,189.0,84.0,29,7.01,0.0,...,0.00,178,45.0,-3.118503,0.000000,0.067635,145000000.0,112000000.0,178000000.0,74

In [58]:
columns_to_delete = ['Name', 'Height', 'Weight', 'Unnamed: 0']
player_data.drop(columns=columns_to_delete, inplace=True)

# NaN değerlerini ortalama ile doldurma
player_data = player_data.fillna(player_data.mean())

player_data.head()

,Apps,Mins,Mins/Gm,Age,Av Rat,Gls,Gls/90,Shot %,Pen/R,xG,...,Tck R,CA,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Value,Min Transfer Value,Max Transfer Value,Based_encoded
0,12.0,809.0,67.416667,20,7.14,1.0,0.11,0.67,0.0,0.18,...,0.88,84,0.0,0.0,5.555556,0.126823,6000.0,3000.0,9000.0,14
1,15.0,1161.0,77.400000,25,6.84,0.0,0.00,0.38,0.0,0.56,...,0.76,79,0.0,0.0,0.000000,0.129457,1250.0,0.0,2500.0,13
2,15.0,1350.0,90.000000,22,6.90,0.0,0.00,0.10,0.0,3.31,...,0.77,87,0.0,0.0,0.000000,0.128000,6000.0,0.0,12000.0,13
3,20.0,1738.0,86.900000,22,7.15,1.0,0.05,0.30,0.0,0.42,...,0.88,95,0.0,0.0,2.380952,0.058631,550000.0,100000.0,1000000.0,6
4,15.0,1384.0,92.266667,19,7.23,4.0,0.26,0.33,0.0,0.00,...,0.93,83,0.0,0.0,0.000000,0.016040,82000.0,14000.0,150000.0,12

In [89]:
def assign_position(row):
    # Kaleci için kriterler
    if (row['Saves'] > 10 or row['Saves/xSv%'] > 0.1 or row['Sv %'] > 0.7 or 
        row['Svh'] > 10 or row['Svt'] > 20 or row['Pens Saved Ratio'] > 0.05):
        return 'Goalkeeper'
    # Defans için kriterler
    elif (row['Tck R'] > 0.5 or row['Int/90'] > 1.0 or row['Clear'] > 30 or 
          row['Hdr %'] > 30 or row['Fls'] > 10 or row['Aer A/90'] > 2):
        return 'Defender'
    # Orta Saha için kriterler
    elif (row['Pas %'] > 70 or row['Drb/90'] > 1.5 or row['Asts/90'] > 0.2 or 
          row['K Ps/90'] > 1.5 or row['Cr C/A'] > 0.3 or row['Tck R'] > 0.4):
        return 'Midfielder'
    # Forvet için kriterler
    elif (row['Gls'] > 10 or row['Gls/90'] > 0.3 or row['Shot %'] > 0.2 or 
          row['xG'] > 5 or row['Ch C/90'] > 1 or row['Drb/90'] > 3):
        return 'Forward'
    else:
        return 'Midfielder'  # Default to Midfielder if no other criteria are met

# Yeni mevki sütunu ekleme
player_data['Position'] = player_data.apply(assign_position, axis=1)

player_data

,Apps,Mins,Mins/Gm,Age,Av Rat,Gls,Gls/90,Shot %,Pen/R,xG,...,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Value,Min Transfer Value,Max Transfer Value,Based_encoded,Position_encoded,Position
0,12.0,809.0,67.416667,20,7.14,1.0,0.11,0.67,0.0,0.18,...,0.0,0.000000,5.555556,0.126823,6000.0,3000.0,9000.0,14,0,Defender
1,15.0,1161.0,77.400000,25,6.84,0.0,0.00,0.38,0.0,0.56,...,0.0,0.000000,0.000000,0.129457,1250.0,0.0,2500.0,13,0,Defender
2,15.0,1350.0,90.000000,22,6.90,0.0,0.00,0.10,0.0,3.31,...,0.0,0.000000,0.000000,0.128000,6000.0,0.0,12000.0,13,0,Defender
3,20.0,1738.0,86.900000,22,7.15,1.0,0.05,0.30,0.0,0.42,...,0.0,0.000000,2.380952,0.058631,550000.0,100000.0,1000000.0,6,0,Defender
4,15.0,1384.0,92.266667,19,7.23,4.0,0.26,0.33,0.0,0.00,...,0.0,0.000000,0.000000,0.016040,82000.0,14000.0,150000.0,12,0,Defender
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,11.0,924.0,84.000000,36,7.15,0.0,0.00,0.29,0.0,0.12,...,0.0,0.000000,0.000000,0.123268,15000000.0,12000000.0,18000000.0,25,0,Defender
1118,13.0,1129.0,86.846154,28,7.33,1.0,0.08,0.17,0.0,0.29,...,0.0,0.000000,3.448276,0.126749,113500000.0,99000000.0,128000000.0,25,0,Defender
1119,19.0,1710.0,90.000000,30,7.42,0.0,0.00,0.00,0.0,0.00,...,48.0,-0.848956,0.000000,0.072982,198500000.0,172000000.0,225000000.0,74,2,Goalkeeper
1120,17.0,1463.0,86.058824,29,7.36,0.0,0.00,0.33,0.0,1.04,...,0.0,0.000000,0.000000,0.107792,114000000.0,101000000.0,127000000.0,24,0,Defender
1121,19.0,1687.0,88.789474,29,7.01,0.0,0.00,0.00,0.0,0.00,...,45.0,-3.118503,0.000000,0.067635,145000000.0,112000000.0,178000000.0,74,2,Goalkeeper

In [90]:
from sklearn.preprocessing import LabelEncoder

# Label Encoder oluşturma
le = LabelEncoder()

# Mevkileri sayısal değerlere dönüştürme
player_data['Position_encoded'] = le.fit_transform(player_data['Position'])

# Mevkilerin sayısal karşılıklarını yazdırma
print(dict(zip(le.classes_, le.transform(le.classes_))))

{'Defender': 0, 'Goalkeeper': 1, 'Midfielder': 2}

In [91]:
player_data.drop(columns='Position', inplace=True)

In [92]:
player_data

,Apps,Mins,Mins/Gm,Age,Av Rat,Gls,Gls/90,Shot %,Pen/R,xG,...,CA,Saves,Saves/xSv%,Gls/xG,Dist/Mins,Value,Min Transfer Value,Max Transfer Value,Based_encoded,Position_encoded
0,12.0,809.0,67.416667,20,7.14,1.0,0.11,0.67,0.0,0.18,...,84,0.0,0.000000,5.555556,0.126823,6000.0,3000.0,9000.0,14,0
1,15.0,1161.0,77.400000,25,6.84,0.0,0.00,0.38,0.0,0.56,...,79,0.0,0.000000,0.000000,0.129457,1250.0,0.0,2500.0,13,0
2,15.0,1350.0,90.000000,22,6.90,0.0,0.00,0.10,0.0,3.31,...,87,0.0,0.000000,0.000000,0.128000,6000.0,0.0,12000.0,13,0
3,20.0,1738.0,86.900000,22,7.15,1.0,0.05,0.30,0.0,0.42,...,95,0.0,0.000000,2.380952,0.058631,550000.0,100000.0,1000000.0,6,0
4,15.0,1384.0,92.266667,19,7.23,4.0,0.26,0.33,0.0,0.00,...,83,0.0,0.000000,0.000000,0.016040,82000.0,14000.0,150000.0,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,11.0,924.0,84.000000,36,7.15,0.0,0.00,0.29,0.0,0.12,...,156,0.0,0.000000,0.000000,0.123268,15000000.0,12000000.0,18000000.0,25,0
1118,13.0,1129.0,86.846154,28,7.33,1.0,0.08,0.17,0.0,0.29,...,163,0.0,0.000000,3.448276,0.126749,113500000.0,99000000.0,128000000.0,25,0
1119,19.0,1710.0,90.000000,30,7.42,0.0,0.00,0.00,0.0,0.00,...,180,48.0,-0.848956,0.000000,0.072982,198500000.0,172000000.0,225000000.0,74,1
1120,17.0,1463.0,86.058824,29,7.36,0.0,0.00,0.33,0.0,1.04,...,164,0.0,0.000000,0.000000,0.107792,114000000.0,101000000.0,127000000.0,24,0
1121,19.0,1687.0,88.789474,29,7.01,0.0,0.00,0.00,0.0,0.00,...,178,45.0,-3.118503,0.000000,0.067635,145000000.0,112000000.0,178000000.0,74,1

In [93]:
# Veriyi mevkilere göre ayırma
defender_data = player_data[player_data['Position_encoded'] == 0]
forward_data = player_data[player_data['Position_encoded'] == 1]
goalkeeper_data = player_data[player_data['Position_encoded'] == 2]
midfielder_data = player_data[player_data['Position_encoded'] == 3]

X_def = defender_data.drop(columns=['Value', 'Position_encoded'])
y_def = defender_data['Value']

X_fwd = forward_data.drop(columns=['Value', 'Position_encoded'])
y_fwd = forward_data['Value']

X_gk = goalkeeper_data.drop(columns=['Value', 'Position_encoded'])
y_gk = goalkeeper_data['Value']

X_mid = midfielder_data.drop(columns=['Value', 'Position_encoded'])
y_mid = midfielder_data['Value']

In [87]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

def get_feature_importance(X, y):
    model = RandomForestRegressor(random_state=42)
    model.fit(X, y)
    importances = model.feature_importances_
    feature_importance = pd.DataFrame({'Feature': X.columns, 'Importance': importances})
    return feature_importance.sort_values(by='Importance', ascending=False)

# Her mevki için özellik önemlerini hesaplama
feature_importance_def = get_feature_importance(X_def, y_def)
feature_importance_fwd = get_feature_importance(X_fwd, y_fwd)
feature_importance_gk = get_feature_importance(X_gk, y_gk)
feature_importance_mid = get_feature_importance(X_mid, y_mid)

print("Defender Feature Importances:\n", feature_importance_def.head(10))
print("Forward Feature Importances:\n", feature_importance_fwd.head(10))
print("Goalkeeper Feature Importances:\n", feature_importance_gk.head(10))
print("Midfielder Feature Importances:\n", feature_importance_mid.head(10))

Defender Feature Importances:
                Feature  Importance
39  Max Transfer Value    0.776329
38  Min Transfer Value    0.193389
33                  CA    0.008570
17               Hdr %    0.006286
0                 Apps    0.002126
10             Ch C/90    0.002041
16            Distance    0.001916
1                 Mins    0.001497
7               Shot %    0.001167
36              Gls/xG    0.000846
Forward Feature Importances:
              Feature  Importance
0               Apps         0.0
21             Clear         0.0
23             xSv %         0.0
24              Sv %         0.0
25               Svh         0.0
26               Svt         0.0
27               Svp         0.0
28  Pens Saved Ratio         0.0
29               PoM         0.0
30          Aer A/90         0.0
Goalkeeper Feature Importances:
                Feature  Importance
39  Max Transfer Value    0.537386
38  Min Transfer Value    0.366471
33                  CA    0.051335
22              Con/90    0.005785
4               Av Rat    0.005424
24                Sv %    0.004585
40       Based_encoded    0.004399
25                 Svh    0.003931
35          Saves/xSv%    0.003841
23               xSv %    0.002515
Midfielder Feature Importances:
                Feature  Importance
33                  CA    0.125653
4               Av Rat    0.114897
2              Mins/Gm    0.096599
39  Max Transfer Value    0.091613
25                 Svh    0.070254
34               Saves    0.068208
13               Pas %    0.056998
22              Con/90    0.051344
24                Sv %    0.050007
3                  Age    0.046966

In [88]:
def select_top_features(feature_importance, top_n=10):
    return feature_importance.head(top_n)['Feature'].values

top_features_def = select_top_features(feature_importance_def, top_n=10)
top_features_fwd = select_top_features(feature_importance_fwd, top_n=10)
top_features_gk = select_top_features(feature_importance_gk, top_n=10)
top_features_mid = select_top_features(feature_importance_mid, top_n=10)

# Tüm önemli özellikleri birleştirme
selected_features = set(top_features_def) | set(top_features_fwd) | set(top_features_gk) | set(top_features_mid)
selected_features = list(selected_features)

print("Selected Features:\n", selected_features)

Selected Features:
 ['Shot %', 'Ch C/90', 'Max Transfer Value', 'Age', 'CA', 'Apps', 'Hdr %', 'Min Transfer Value', 'Gls/xG', 'Pens Saved Ratio', 'Pas %', 'Aer A/90', 'Based_encoded', 'Sv %', 'Mins', 'Clear', 'Svt', 'Av Rat', 'Mins/Gm', 'Svh', 'Saves', 'PoM', 'Distance', 'Svp', 'xSv %', 'Saves/xSv%', 'Con/90']

In [72]:
from sklearn.model_selection import train_test_split, cross_val_predict 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.svm import SVR, LinearSVR
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import classification_report, accuracy_score, recall_score, precision_score, confusion_matrix, roc_curve, roc_auc_score
from sklearn.metrics import confusion_matrix  
import warnings
warnings.filterwarnings('ignore')
plt.style.use('fivethirtyeight')

X_selected = player_data[selected_features + ['Position_encoded']]
y = player_data['Value']

# K-Fold Cross-Validation fonksiyonu
def k_fold_cross_validation(X, y, model, num_folds=10):
    num_instances = len(X)
    fold_size = num_instances // num_folds

    indices = np.arange(num_instances)
    np.random.seed(123)
    np.random.shuffle(indices)

    X_shuffled = X.iloc[indices].reset_index(drop=True)
    y_shuffled = y.iloc[indices].reset_index(drop=True)

    best_model = None  
    best_score = float('-inf')
    scores = []
    predictions = []
    mse_scores = []
    mae_scores = []
    r2_scores = []

    for i in range(num_folds):
        start = i * fold_size
        end = (i + 1) * fold_size if i < num_folds - 1 else num_instances

        X_test_fold = X_shuffled.iloc[start:end]
        y_test_fold = y_shuffled.iloc[start:end]
        X_train_fold = pd.concat([X_shuffled.iloc[:start], X_shuffled.iloc[end:]], axis=0)
        y_train_fold = pd.concat([y_shuffled.iloc[:start], y_shuffled.iloc[end:]], axis=0)

        model.fit(X_train_fold, y_train_fold)
        y_pred = model.predict(X_test_fold)

        score = model.score(X_test_fold, y_test_fold)
        scores.append(score)
        predictions.extend(y_pred)

        mse = mean_squared_error(y_test_fold, y_pred)
        mae = mean_absolute_error(y_test_fold, y_pred)
        r2 = r2_score(y_test_fold, y_pred)

        mse_scores.append(mse)
        mae_scores.append(mae)
        r2_scores.append(r2)

        if score > best_score:
            best_score = score
            best_model = model

    print("Best Model Score:", best_score)
    print("Average MSE Score:", np.mean(mse_scores))
    print("Average MAE Score:", np.mean(mae_scores))
    print("Average R2 Score:", np.mean(r2_scores))

    return best_model, scores, predictions, mse_scores, mae_scores, r2_scores

# Model sözlüğü oluşturma
models = {
    'RandomForestRegressor': RandomForestRegressor(),
    'KNeighborsRegressor': KNeighborsRegressor(),
    'AdaBoostRegressor': AdaBoostRegressor(),
    'SVR': SVR(),
    'LinearSVR': LinearSVR(),
    'MLPRegressor': MLPRegressor(),

}

# Her bir model için cross-validation sonuçlarını yazdırma
for model_name, model in models.items():
    print(f"{model_name} modeli için cross-validation sonuçları:")
    best_model, scores, predictions, mse_scores, mae_scores, r2_scores = k_fold_cross_validation(X_selected, y, model)
    print("\n---------------------------------------------------------------------\n")

RandomForestRegressor modeli için cross-validation sonuçları:
Best Model Score: 0.9988778337776075
Average MSE Score: 10261860799896.66
Average MAE Score: 496679.3734674969
Average R2 Score: 0.9920554183926515

----------------------------------------------------------------------------

KNeighborsRegressor modeli için cross-validation sonuçları:
Best Model Score: 0.9995943773422278
Average MSE Score: 8866575740286.371
Average MAE Score: 418982.379962406
Average R2 Score: 0.993494958830413

----------------------------------------------------------------------------

AdaBoostRegressor modeli için cross-validation sonuçları:
Best Model Score: 0.9895185429610331
Average MSE Score: 13697250272149.705
Average MAE Score: 2871053.648356795
Average R2 Score: 0.9823593299161605

----------------------------------------------------------------------------

SVR modeli için cross-validation sonuçları:
Best Model Score: -0.08521800450988137
Average MSE Score: 1029237724917301.8
Average MAE Score: 11212415.748412827
Average R2 Score: -0.1296270633919227

----------------------------------------------------------------------------

LinearSVR modeli için cross-validation sonuçları:
Best Model Score: 0.9999990809184789
Average MSE Score: 3978423901927.0195
Average MAE Score: 361723.5468528856
Average R2 Score: 0.9972723750295813

----------------------------------------------------------------------------

MLPRegressor modeli için cross-validation sonuçları:
Best Model Score: 0.9999816467284356
Average MSE Score: 401022660587.7018
Average MAE Score: 172590.6174745033
Average R2 Score: 0.9992965707993919

----------------------------------------------------------------------------